/*----- PROTECTED REGION ID(SurfaceConceptTDCStateMachine.cpp) ENABLED START -----*/
/*
 * The MIT License
 *
 * Copyright 2016-2018 Surface Concept GmbH
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        SurfaceConceptTDCStateMachine.cpp
//
// description : State machine file for the SurfaceConceptTDC class
//
// project :     SurfaceConceptTDC
//
// This file is part of Tango device class.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <SurfaceConceptTDC.h>

/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::SurfaceConceptTDCStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace SurfaceConceptTDC_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SurfaceConceptTDC::is_DeviceID_allowed()
 *	Description : Execution allowed for DeviceID attribute
 */
//--------------------------------------------------------
bool SurfaceConceptTDC::is_DeviceID_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DeviceID attribute in read access.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::DeviceIDStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::DeviceIDStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SurfaceConceptTDC::is_ExposureLive_allowed()
 *	Description : Execution allowed for ExposureLive attribute
 */
//--------------------------------------------------------
bool SurfaceConceptTDC::is_ExposureLive_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureLive attribute in Write access.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::ExposureLiveStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::ExposureLiveStateAllowed_WRITE

	//	Not any excluded states for ExposureLive attribute in read access.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::ExposureLiveStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::ExposureLiveStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SurfaceConceptTDC::is_ExposureAccu_allowed()
 *	Description : Execution allowed for ExposureAccu attribute
 */
//--------------------------------------------------------
bool SurfaceConceptTDC::is_ExposureAccu_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExposureAccu attribute in Write access.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::ExposureAccuStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::ExposureAccuStateAllowed_WRITE

	//	Not any excluded states for ExposureAccu attribute in read access.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::ExposureAccuStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::ExposureAccuStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SurfaceConceptTDC::is_Start_allowed()
 *	Description : Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool SurfaceConceptTDC::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Start command.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::StartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::StartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SurfaceConceptTDC::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool SurfaceConceptTDC::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::StopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SurfaceConceptTDC::is_AcquisitionStart_allowed()
 *	Description : Execution allowed for AcquisitionStart attribute
 */
//--------------------------------------------------------
bool SurfaceConceptTDC::is_AcquisitionStart_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for AcquisitionStart command.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::AcquisitionStartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::AcquisitionStartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SurfaceConceptTDC::is_AcquisitonStop_allowed()
 *	Description : Execution allowed for AcquisitonStop attribute
 */
//--------------------------------------------------------
bool SurfaceConceptTDC::is_AcquisitonStop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for AcquisitonStop command.
	/*----- PROTECTED REGION ID(SurfaceConceptTDC::AcquisitonStopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SurfaceConceptTDC::AcquisitonStopStateAllowed
	return true;
}

}	//	End of namespace
